version: "3"
services:
  emqx:
    image: emqx/emqx:v4.0.0
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
      - "8084:8084"
      - "8883:8883"
      - "8083:8083"
    restart: always
    networks:
      - net
networks:
  net:
    external: true
      