version: '3.8'

services:
  deepin-webtop:
    image: chenchongbiao/deepin-webtop
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepin-webtop
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
    ports:
      - 3002:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
      - https_proxy=http://10.20.42.187:7890
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=fonts-noto-cjk
      - LC_ALL=zh_CN.UTF-8
    volumes:
      - ./data:/config
      # - ./startwm.sh:/defaults/startwm.sh
      # - ./root/kasminit:/kasminit
      - /var/run/docker.sock:/var/run/docker.sock #optional
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    cgroup_parent: docker.slice
    restart: unless-stopped
