version: "3"
services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8
    volumes:
    # 挂载配置文件
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d 
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    restart: always
    networks:
      - net
networks:
  net:
    external: true
      