name: build docker

on:
  push:
    branches: [ 'master' ]
    paths:
      - '**/webtop/**'
  workflow_dispatch:

env:
  owner: chenchongbiao

jobs:
  build:
    name: Build webtop image
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build images
        run: |
          # pushd webtop/debian/gxde
          # docker buildx build --load  --platform linux/amd64 -t ${{ env.owner }}/webtop:debian-gxde .
          # popd

          pushd webtop/deepin/dde20
          docker buildx build --load --platform linux/amd64 -t ${{ env.owner }}/webtop:deepin-dde20 .
          popd

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker image push
        run: |
          # docker push ${{ env.owner }}/webtop:debian-gxde
          docker push ${{ env.owner }}/webtop:deepin-dde20
